possibilities:
- state:
  - robot_inside_habitat
  - door_habitat_airlock_unlocked_opened
  action: enter_airlock_from_habitat
  next_state:
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - door_habitat_airlock_unlocked_opened
  action: enter_habitat_from_airlock
  next_state:
  - robot_inside_habitat
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - door_airlock_surface_unlocked_opened
  action: enter_surface_from_airlock
  next_state:
  - robot_outside_habitat
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_outside_habitat
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_surface
  next_state:
  - robot_inside_airlock
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_inside_habitat
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  action: enter_airlock_from_habitat
  next_state:
  - robot_has_key
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_locked_closed
  action: unlock_open_door_habitat_airlock
  next_state:
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  validity: true
- state:
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  action: enter_habitat_from_airlock
  next_state:
  - robot_has_key
  - robot_inside_habitat
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - robot_has_key
  - door_airlock_surface_unlocked_opened
  action: enter_surface_from_airlock
  next_state:
  - robot_has_key
  - robot_outside_habitat
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_outside_habitat
  - robot_has_key
  - door_airlock_surface_locked_closed
  action: unlock_open_door_airlock_surface
  next_state:
  - robot_outside_habitat
  - robot_has_key
  - door_airlock_surface_unlocked_opened
  validity: true
- state:
  - robot_outside_habitat
  - robot_has_key
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_surface
  next_state:
  - robot_has_key
  - robot_inside_airlock
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_inside_habitat
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_locked_closed
  action: enter_airlock_from_habitat
  next_state:
  - door_airlock_surface_locked_closed
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_habitat
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_habitat
  next_state:
  - door_airlock_surface_unlocked_opened
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  validity: false
- state:
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_unlocked_opened
  action: enter_surface_from_airlock
  next_state:
  - door_habitat_airlock_locked_closed
  - robot_outside_habitat
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_locked_closed
  action: enter_habitat_from_airlock
  next_state:
  - door_airlock_surface_locked_closed
  - robot_inside_habitat
  - door_habitat_airlock_locked_closed
  validity: true
- state: &id001
  - robot_inside_airlock
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  action: enter_surface_from_airlock
  next_state:
  - door_habitat_airlock_unlocked_opened
  - robot_outside_habitat
  - door_airlock_surface_locked_closed
  validity: true
- state: *id001
  action: enter_habitat_from_airlock
  next_state:
  - door_airlock_surface_unlocked_opened
  - robot_inside_habitat
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_outside_habitat
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_surface
  next_state:
  - door_habitat_airlock_locked_closed
  - robot_inside_airlock
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_outside_habitat
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_surface
  next_state:
  - door_habitat_airlock_unlocked_opened
  - robot_inside_airlock
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_inside_habitat
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_locked_closed
  action: enter_airlock_from_habitat
  next_state:
  - robot_has_key
  - door_airlock_surface_locked_closed
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_habitat
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_habitat
  next_state:
  - robot_has_key
  - door_airlock_surface_unlocked_opened
  - robot_inside_airlock
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_locked_closed
  action: unlock_open_door_habitat_airlock
  next_state:
  - robot_inside_airlock
  - robot_has_key
  - door_airlock_surface_locked_closed
  - door_habitat_airlock_unlocked_opened
  validity: true
- state: &id002
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_unlocked_opened
  action: unlock_open_door_habitat_airlock
  next_state:
  - robot_inside_airlock
  - robot_has_key
  - door_airlock_surface_unlocked_opened
  - door_habitat_airlock_unlocked_opened
  validity: true
- state: *id002
  action: enter_surface_from_airlock
  next_state:
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - robot_outside_habitat
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_locked_closed
  action: enter_habitat_from_airlock
  next_state:
  - robot_has_key
  - door_airlock_surface_locked_closed
  - robot_inside_habitat
  - door_habitat_airlock_locked_closed
  validity: true
- state: &id003
  - robot_inside_airlock
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  action: enter_surface_from_airlock
  next_state:
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - robot_outside_habitat
  - door_airlock_surface_locked_closed
  validity: true
- state: *id003
  action: enter_habitat_from_airlock
  next_state:
  - robot_has_key
  - door_airlock_surface_unlocked_opened
  - robot_inside_habitat
  - door_habitat_airlock_locked_closed
  validity: true
- state:
  - robot_outside_habitat
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_locked_closed
  action: unlock_open_door_airlock_surface
  next_state:
  - robot_outside_habitat
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_unlocked_opened
  validity: true
- state:
  - robot_outside_habitat
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_surface
  next_state:
  - robot_has_key
  - door_habitat_airlock_locked_closed
  - robot_inside_airlock
  - door_airlock_surface_locked_closed
  validity: true
- state:
  - robot_outside_habitat
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_locked_closed
  action: unlock_open_door_airlock_surface
  next_state:
  - robot_outside_habitat
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  validity: true
- state:
  - robot_outside_habitat
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - door_airlock_surface_unlocked_opened
  action: enter_airlock_from_surface
  next_state:
  - robot_has_key
  - door_habitat_airlock_unlocked_opened
  - robot_inside_airlock
  - door_airlock_surface_locked_closed
  validity: true
