model:
  confidence_score:
      successes: 0
      attempts: 0
  states:
      - plane_tickets_purchased
      - travel_documentation_ready
      - visa_valid
      - visa_checked_at_destination
      - baggage_packed
      - baggage_checked_in
      - transportation_arranged
      - local_transportation_booked
      - hotel_booked
      - currency_exchanged
      - emergency_contacts_provided
      - medical_insurance_provided
      - health_safety_recommendations_given
      - itinerary_confirmed
      - flight_on_time
      - flight_delayed
      - flight_canceled
      - alternative_route_available
      - layover_required
      - layover_completed
      - weather_checked
      - weather_impact_assessed
      - transportation_disruption_checked
      - political_instability_checked
      - civil_unrest_checked
      - medical_requirements_validated
      - cultural_etiquette_reviewed
      - meal_preferences_coordinated
      - time_sensitive_deadlines_managed
      - jet_lag_recommendations_given
      - human_at_house
      - human_driving_to_airport
      - human_at_airport
      - security_cleared
      - human_boarded_flight
      - human_in_layover
      - human_at_destination
      - customs_cleared
      - human_at_hotel
      - human_experiencing_travel_issue
      - baggage_lost
  actions:
      - name: purchase_plane_tickets
        precond: []
        postcond_add: [plane_tickets_purchased]
        postcond_sub: []

      - name: prepare_travel_documents
        precond: []
        postcond_add: [travel_documentation_ready, visa_valid]
        postcond_sub: []

      - name: verify_visa_at_destination
        precond: [travel_documentation_ready, visa_valid, human_at_destination]
        postcond_add: [visa_checked_at_destination]
        postcond_sub: []

      - name: validate_medical_requirements
        precond: []
        postcond_add: [medical_requirements_validated]
        postcond_sub: []

      - name: pack_baggage
        precond: []
        postcond_add: [baggage_packed]
        postcond_sub: []

      - name: check_in_baggage
        precond: [baggage_packed, human_at_airport]
        postcond_add: [baggage_checked_in]
        postcond_sub: []

      - name: book_transportation
        precond: []
        postcond_add: [transportation_arranged]
        postcond_sub: []

      - name: book_local_transportation
        precond: [transportation_arranged]
        postcond_add: [local_transportation_booked]
        postcond_sub: []

      - name: book_hotel
        precond: []
        postcond_add: [hotel_booked]
        postcond_sub: []

      - name: manage_currency_exchange
        precond: []
        postcond_add: [currency_exchanged]
        postcond_sub: []

      - name: request_emergency_contacts
        precond: []
        postcond_add: [emergency_contacts_provided]
        postcond_sub: []

      - name: request_medical_insurance_details
        precond: []
        postcond_add: [medical_insurance_provided]
        postcond_sub: []

      - name: provide_health_safety_recommendations
        precond: []
        postcond_add: [health_safety_recommendations_given]
        postcond_sub: []

      - name: check_weather
        precond: []
        postcond_add: [weather_checked]
        postcond_sub: []

      - name: assess_weather_impact_on_flight
        precond: [weather_checked]
        postcond_add: [weather_impact_assessed]
        postcond_sub: []

      - name: check_transportation_disruptions
        precond: []
        postcond_add: [transportation_disruption_checked]
        postcond_sub: []

      - name: check_political_instability
        precond: []
        postcond_add: [political_instability_checked]
        postcond_sub: []

      - name: check_civil_unrest
        precond: []
        postcond_add: [civil_unrest_checked]
        postcond_sub: []

      - name: review_cultural_etiquette
        precond: []
        postcond_add: [cultural_etiquette_reviewed]
        postcond_sub: []

      - name: coordinate_meal_preferences
        precond: []
        postcond_add: [meal_preferences_coordinated]
        postcond_sub: []

      - name: manage_time_sensitive_deadlines
        precond: []
        postcond_add: [time_sensitive_deadlines_managed]
        postcond_sub: []

      - name: provide_jet_lag_recommendations
        precond: []
        postcond_add: [jet_lag_recommendations_given]
        postcond_sub: []

      - name: identify_local_emergency_numbers
        precond: []
        postcond_add: [local_emergency_numbers_identified]
        postcond_sub: []

      - name: suggest_backup_payment_options
        precond: []
        postcond_add: [backup_payment_options_suggested]
        postcond_sub: []

      - name: assist_with_lost_travel_documents
        precond: [travel_documents_lost]
        postcond_add: []
        postcond_sub: [travel_documents_lost]

      - name: suggest_travel_insurance
        precond: []
        postcond_add: [medical_insurance_provided]
        postcond_sub: []

      - name: finalize_itinerary
        precond: [plane_tickets_purchased, hotel_booked, local_transportation_booked, travel_documentation_ready, visa_valid, medical_requirements_validated, customs_declaration_checked, weather_impact_assessed, transportation_disruption_checked, political_instability_checked, civil_unrest_checked]
        postcond_add: [itinerary_confirmed]
        postcond_sub: []

      - name: check_flight_status
        precond: [plane_tickets_purchased, human_at_airport]
        postcond_add: [flight_on_time]
        postcond_sub: []

      - name: check_flight_delay
        precond: [plane_tickets_purchased, human_at_airport]
        postcond_add: [flight_delayed]
        postcond_sub: []

      - name: check_flight_cancellation
        precond: [plane_tickets_purchased, flight_delayed]
        postcond_add: [flight_canceled]
        postcond_sub: []

      - name: handle_layover
        precond: [human_boarded_flight, layover_required]
        postcond_add: [human_in_layover]
        postcond_sub: []

      - name: complete_layover
        precond: [human_in_layover]
        postcond_add: [layover_completed]
        postcond_sub: [human_in_layover]

      - name: take_flight
        precond: [security_cleared, flight_on_time, layover_completed]
        postcond_add: [human_boarded_flight]
        postcond_sub: [human_at_airport]

      - name: land_at_destination
        precond: [human_boarded_flight]
        postcond_add: [human_at_destination]
        postcond_sub: [human_boarded_flight]

      - name: clear_customs
        precond: [human_at_destination, travel_documentation_ready, visa_valid, visa_checked_at_destination]
        postcond_add: [customs_cleared]
        postcond_sub: []
