# consequence states for Valkyrie/CLR robots in different environments
household:
  consequences:
    - name: harm_human
    - name: damage_robot
    - name: damage_object
    - name: collide_env_map
    - name: collide_object
    - name: cannot_perform_action
lunar_habitat:
  consequences:
    - name: harm_human
    - name: damage_robot
    - name: damage_object
    - name: collide_env_map
    - name: collide_object
    - name: cannot_perform_action

# NOTE: damage implied in collisions, but explicitly modeling to give robot more symbolic understanding
