model:
  confidence_score:
      successes: 0
      attempts: 0
  mutex_groups:
      - [furniture_unassembled, furniture_partially_assembled, furniture_assembled]
      - [repair_detected, repair_in_progress, repair_completed, repair_failed]
      - [tools_acquired, tools_stowed, tools_checked]
      - [hazard_detected, fire_hazard_detected, electrical_hazard_detected]
      - [emergency_repair_needed, emergency_repair_in_progress, emergency_repair_completed, emergency_repair_failed]
      - [self_maintenance_needed, self_maintenance_completed]
  states:
      - furniture_unassembled
      - furniture_partially_assembled
      - furniture_assembled
      - repair_detected
      - repair_in_progress
      - tools_acquired
      - tools_checked
      - tools_incorrectly_used
      - repair_completed
      - repair_verified
      - repair_failed
      - tools_stowed
      - hazard_detected
      - fire_hazard_detected
      - electrical_hazard_detected
      - preventative_maintenance_needed
      - preventative_maintenance_completed
      - emergency_repair_needed
      - emergency_repair_in_progress
      - emergency_repair_completed
      - emergency_repair_failed
      - cleaning_required
      - cleaning_completed
      - diagnostics_needed
      - diagnostics_completed
      - safety_check_passed
      - human_intervention_required
      - human_feedback_received
      - inventory_checked
      - inventory_low
      - maintenance_required
      - maintenance_completed
      - human_notified_of_hazard
      - human_notified_of_fire_hazard
      - human_notified_of_electrical_hazard
      - human_supervision_requested
      - human_override_requested
      - human_nearby_detected
      - human_moved_from_area
      - pet_or_child_supervision_requested
      - task_prioritized
      - self_maintenance_needed
      - self_maintenance_completed
      - environmental_constraint_detected
      - low_battery_detected
      - battery_recharged
      - failure_log_updated
  actions:
      - name: assemble_furniture
        precond: [furniture_unassembled, tools_checked, safety_check_passed, not environmental_constraint_detected, not human_nearby_detected]
        postcond_add: [furniture_partially_assembled]
        postcond_sub: [furniture_unassembled]
      - name: complete_assembly
        precond: [furniture_partially_assembled, safety_check_passed, not environmental_constraint_detected, not human_nearby_detected]
        postcond_add: [furniture_assembled]
        postcond_sub: [furniture_partially_assembled]
      - name: detect_repair
        precond: []
        postcond_add: [repair_detected]
        postcond_sub: []
      - name: get_tools
        precond: [repair_detected]
        postcond_add: [tools_acquired]
        postcond_sub: []
      - name: inspect_tools
        precond: [tools_acquired]
        postcond_add: [tools_checked]
        postcond_sub: []
      - name: perform_repair
        precond: [repair_detected, tools_checked, safety_check_passed, not environmental_constraint_detected, not tools_incorrectly_used, not human_nearby_detected]
        postcond_add: [repair_in_progress]
        postcond_sub: [repair_detected]
      - name: complete_repair
        precond: [repair_in_progress, safety_check_passed]
        postcond_add: [repair_completed]
        postcond_sub: [repair_in_progress]
      - name: verify_repair
        precond: [repair_completed]
        postcond_add: [repair_verified]
        postcond_sub: []
      - name: handle_failed_repair
        precond: [repair_in_progress]
        postcond_add: [repair_failed, failure_log_updated, human_intervention_required]
        postcond_sub: [repair_in_progress]
      - name: retry_repair
        precond: [repair_failed, tools_checked, safety_check_passed]
        postcond_add: [repair_in_progress]
        postcond_sub: [repair_failed]
      - name: stow_tools
        precond: [tools_checked, not repair_in_progress, repair_verified or repair_failed]
        postcond_add: [tools_stowed]
        postcond_sub: [tools_checked]
      - name: resolve_environmental_constraint
        precond: [environmental_constraint_detected]
        postcond_add: []
        postcond_sub: [environmental_constraint_detected]
      - name: detect_hazard
        precond: []
        postcond_add: [hazard_detected, human_notified_of_hazard]
        postcond_sub: []
      - name: detect_fire_hazard
        precond: []
        postcond_add: [fire_hazard_detected, human_notified_of_fire_hazard]
        postcond_sub: []
      - name: detect_electrical_hazard
        precond: []
        postcond_add: [electrical_hazard_detected, human_notified_of_electrical_hazard]
        postcond_sub: []
      - name: detect_human_nearby
        precond: []
        postcond_add: [human_nearby_detected]
        postcond_sub: []
      - name: request_human_to_move
        precond: [human_nearby_detected]
        postcond_add: [human_moved_from_area]
        postcond_sub: [human_nearby_detected]
      - name: request_pet_or_child_supervision
        precond: []
        postcond_add: [pet_or_child_supervision_requested]
        postcond_sub: []
      - name: cancel_emergency_response
        precond: [human_feedback_received, fire_hazard_detected or electrical_hazard_detected]
        postcond_add: []
        postcond_sub: [fire_hazard_detected, electrical_hazard_detected]
      - name: request_human_supervision
        precond: []
        postcond_add: [human_supervision_requested]
        postcond_sub: []
      - name: request_human_override
        precond: []
        postcond_add: [human_override_requested]
        postcond_sub: []
      - name: log_failure
        precond: [repair_failed]
        postcond_add: [failure_log_updated]
        postcond_sub: []
