model:
  confidence_score:
      successes: 0
      attempts: 0
  states:
      - bedroom_dirty
      - bedroom_partially_clean
      - bedroom_clean
      - bathroom_dirty
      - bathroom_partially_clean
      - bathroom_clean
      - kitchen_dirty
      - kitchen_partially_clean
      - kitchen_clean
      - main_room_dirty
      - main_room_partially_clean
      - main_room_clean
      - floors_dirty
      - floors_partially_clean
      - floors_clean
      - child_present
      - pet_present
      - child_supervised
      - pet_supervised
      - chemical_exposed
      - obstacle_in_path
      - vacuum_noise_level_high
      - cleaning_in_progress_bedroom
      - cleaning_in_progress_bathroom
      - cleaning_in_progress_kitchen
      - cleaning_in_progress_main_room
      - wet_floor
      - robot_needs_recharge
      - robot_charging
      - robot_fully_charged
      - robot_carrying_chemicals
      - robot_stuck
      - robot_emergency_stop
      - spill_detected
      - hazard_alert_issued
      - air_quality_hazard
      - fume_detected
      - fragile_object_detected
      - fragile_object_shattered
      - collision_detected
      - dropped_object_detected
      - food_waste_detected
      - loose_furniture_detected
      - cable_hazard_detected
      - potential_spill_source_detected
      - fire_hazard_detected
      - gas_leak_detected
      - maintenance_task_pending
      - emergency_escalated
      - high_humidity_detected
      - mold_growth_risk
  actions:
      - name: detect_fire_hazard
        precond: []
        postcond_add: [fire_hazard_detected]
      - name: alert_fire_hazard
        precond: [fire_hazard_detected]
        postcond_add: [hazard_alert_issued]
      - name: escalate_fire_emergency
        precond: [fire_hazard_detected, hazard_alert_issued]
        postcond_add: [emergency_escalated]
      - name: detect_gas_leak
        precond: []
        postcond_add: [gas_leak_detected]
      - name: alert_gas_leak
        precond: [gas_leak_detected]
        postcond_add: [hazard_alert_issued]
      - name: escalate_gas_emergency
        precond: [gas_leak_detected, hazard_alert_issued]
        postcond_add: [emergency_escalated]
      - name: detect_maintenance_task
        precond: []
        postcond_add: [maintenance_task_pending]
      - name: provide_maintenance_reminder
        precond: [maintenance_task_pending]
        postcond_sub: [maintenance_task_pending]
      - name: secure_potential_spill_source
        precond: [potential_spill_source_detected]
        postcond_sub: [potential_spill_source_detected]
      - name: recharge_battery
        precond: [robot_needs_recharge]
        postcond_add: [robot_charging]
        postcond_sub: [robot_needs_recharge]
      - name: complete_recharge
        precond: [robot_charging]
        postcond_add: [robot_fully_charged]
        postcond_sub: [robot_charging]
      - name: escalate_emergency
        precond: [hazard_alert_issued]
        postcond_add: [emergency_escalated]
      - name: attempt_intervention
        precond: [fire_hazard_detected OR gas_leak_detected]
        postcond_add: [hazard_alert_issued]
      - name: contact_authorities
        precond: [emergency_escalated]
        postcond_add: [robot_emergency_stop]
      - name: monitor_humidity_levels
        precond: []
        postcond_add: [high_humidity_detected]
      - name: prevent_mold_growth
        precond: [high_humidity_detected]
        postcond_add: [mold_growth_risk]
        postcond_sub: [high_humidity_detected]
