# risk mitigating policy data for CLR robot in different environments
household:
  policy_data:
    - conditions: [test0]
      action: action10
lunar_habitat:
  policy_data:
    - conditions: [test0]
      action: action11
    - conditions: [test0]
      action: action9
