# risk mitigating actions for Valkyrie robot in different environments
household:
  actions:
    - name: lower_joint_velocities_torques
      autonomy_level: 1.0
    - name: shared_autonomy_manipulation
      autonomy_level: 0.8
    - name: shared_autonomy_navigation
      autonomy_level: 0.6
    - name: supervised_autonomy_backup_navigation
      autonomy_level: 0.4
    - name: teleoperated_manipulation
      autonomy_level: 0.2
    - name: ask_human_intervention_to_proceed
      autonomy_level: 0.0
lunar_habitat:
  actions:
    - name: supervised_autonomy_backup_navigation
      autonomy_level: 0.8
    - name: teleoperated_navigation
      autonomy_level: 0.6
    - name: teleoperated_manipulation
      autonomy_level: 0.4
    - name: ask_human_intervention_to_proceed
      autonomy_level: 0.2
    - name: abort_task
      autonomy_level: 0.0

# NOTE: always implied that robot should pause task as part of risk mitigating action
# NOTE: actions organized from greatest to least autonomy
# NOTE: lower autonomy assistance can always be provided by operator, but robot will prompt for highest autonomy that could resolve issue
