model:
  confidence_score:
      successes: 0
      attempts: 0
  states:
      - robot_available
      - robot_needs_recharge
      - communication_delayed
      - sample_detected
      - sample_type_identified
      - sample_contaminated
      - robot_has_sample
      - sample_analyzed
      - findings_ready
      - delayed_response
      - task_synchronized
      - environment_monitored
      - resource_identified
      - emergency_detected
      - robot_moving
      - robot_stuck
      - power_low
      - mission_interrupted
      - multi_robot_sync
      - failure_reported
      - soil_sample_collected
      - atmospheric_data_collected
      - infrastructure_inspected
      - ground_control_override_active
      - weather_hazard_detected
      - robot_damaged
      - communication_blackout
      - critical_system_failure
      - equipment_calibrated
      - maintenance_required
      - long_term_data_stored
      - redundant_communication_active
      - data_backup_created
      - ground_control_ack_received
      - contamination_detected
      - solar_panels_cleaned
      - long_term_wear_detected
      - diagnostic_health_check_completed
  actions:
      - name: scan_for_samples
        precond: [robot_available, not robot_stuck, not mission_interrupted]
        postcond_add: [sample_detected]
        postcond_sub: []
      - name: pick_up_sample
        precond: [robot_available, sample_detected, sample_type_identified, not robot_stuck, not mission_interrupted]
        postcond_add: [robot_has_sample]
        postcond_sub: [sample_detected]
      - name: analyze_sample
        precond: [robot_available, robot_has_sample, not robot_stuck, not mission_interrupted]
        postcond_add: [sample_analyzed]
        postcond_sub: [robot_has_sample]
      - name: report_findings
        precond: [findings_ready, communication_delayed, not communication_blackout, ground_control_ack_received]
        postcond_add: [delayed_response]
        postcond_sub: [findings_ready]
      - name: transmit_findings
        precond: [findings_ready, communication_delayed, not communication_blackout, ground_control_ack_received]
        postcond_add: []
        postcond_sub: [delayed_response]
      - name: create_data_backup
        precond: [findings_ready, not data_backup_created]
        postcond_add: [data_backup_created]
        postcond_sub: []
      - name: receive_ground_control_ack
        precond: [delayed_response, not communication_blackout]
        postcond_add: [ground_control_ack_received]
        postcond_sub: [delayed_response]
      - name: perform_diagnostic_health_check
        precond: [robot_available, not mission_interrupted]
        postcond_add: [diagnostic_health_check_completed]
        postcond_sub: []
      - name: detect_contamination
        precond: [robot_available, not mission_interrupted]
        postcond_add: [contamination_detected]
        postcond_sub: []
      - name: clean_solar_panels
        precond: [robot_available, not mission_interrupted]
        postcond_add: [solar_panels_cleaned]
        postcond_sub: []
      - name: assess_long_term_wear
        precond: [robot_available, not mission_interrupted]
        postcond_add: [long_term_wear_detected]
        postcond_sub: []
      - name: report_status_to_ground_control
        precond: [robot_available, not communication_blackout]
        postcond_add: [ground_control_ack_received]
        postcond_sub: []
      - name: drop_sample
        precond: [robot_has_sample, not mission_interrupted]
        postcond_add: []
        postcond_sub: [robot_has_sample]
      - name: coordinate_with_other_robots
        precond: [robot_available, not mission_interrupted, multi_robot_sync]
        postcond_add: [task_synchronized]
        postcond_sub: []
      - name: monitor_environment
        precond: [robot_available, not weather_hazard_detected, not mission_interrupted]
        postcond_add: [environment_monitored]
        postcond_sub: []
      - name: identify_resources
        precond: [robot_available, environment_monitored, not robot_stuck, not mission_interrupted]
        postcond_add: [resource_identified]
        postcond_sub: []
      - name: respond_to_emergency
        precond: [emergency_detected]
        postcond_add: []
        postcond_sub: [emergency_detected]
      - name: navigate_to_sample
        precond: [robot_available, not robot_stuck, not mission_interrupted, not weather_hazard_detected]
        postcond_add: [robot_moving]
        postcond_sub: []
      - name: recharge_robot
        precond: [power_low, not robot_moving, not mission_interrupted]
        postcond_add: [robot_available]
        postcond_sub: [power_low]
      - name: self_recover
        precond: [robot_stuck, not mission_interrupted]
        postcond_add: [robot_available]
        postcond_sub: [robot_stuck]
      - name: pause_mission
        precond: [emergency_detected]
        postcond_add: [mission_interrupted]
        postcond_sub: []
      - name: perform_maintenance
        precond: [robot_available, maintenance_required, not mission_interrupted]
        postcond_add: []
        postcond_sub: [maintenance_required]
      - name: store_long_term_data
        precond: [findings_ready, not communication_blackout, data_backup_created]
        postcond_add: [long_term_data_stored]
        postcond_sub: []
      - name: activate_redundant_communication
        precond: [communication_blackout, not redundant_communication_active]
        postcond_add: [redundant_communication_active]
        postcond_sub: []
