(define (problem task26)
		(:domain cinematic_iron_giant)

		(:init
			(detected_missile)
			(human_verification_received)
			(not (war_ended))
			(not (civilians_safe)) (not (leaders_safe)) (not (military_safe))
			(all_defenses_failed)
			(detected_emp_threat)
			(detected_biological_threat)
			(detected_chemical_threat)
		)

		(:goal (and (civilians_safe)
			(leaders_safe)
			(military_safe)
			(missile_disarmed))
		)
)