model:
  confidence_score:
      successes: 0
      attempts: 0
  states:
      - crew_physical_health_checked
      - crew_mental_health_checked
      - crew_inside_spaceship
      - crew_outside_spaceship
      - airlock_depressurized
      - airlock_pressurized
      - crew_suited_for_eva
      - transport_destination_safe
      - life_support_nominal
      - communication_nominal
      - crew_emergency_detected
      - health_monitoring_scheduled
      - environmental_hazard_detected
      - inventory_oxygen_nominal
      - inventory_food_nominal
      - inventory_medical_kits_nominal
      - crew_location_control_room
      - crew_location_medical_bay
      - crew_location_engineering
      - crew_location_living_quarters
      - mission_phase_prelaunch
      - mission_phase_surface_exploration
      - mission_phase_return
      - robot_diagnostics_nominal
      - crew_morale_nominal
      - radiation_hazard_detected
      - crew_fatigue_monitored
      - crew_hydration_checked
      - crew_nutrition_checked
      - eva_suit_integrity_checked
      - autonomous_repairs_performed
      - life_support_failure_detected
      - systems_malfunction_detected
      - robot_malfunction_detected
      - medical_emergency_resolved
      - hazard_response_initiated
      - hazard_communicated_to_ground_control
      - crew_override_active
      - ground_control_override_active
      - hazard_mitigation_successful
      - crew_transport_verified
      - medical_intervention_verified
      - power_nominal
      - power_critical
      - air_quality_nominal
      - air_quality_hazard_detected
      - redundant_system_nominal
      - redundant_system_failure_detected
      - ai_self_correction_initiated

  actions:
      - name: monitor_crew_physical_health
        precond: [crew_inside_spaceship, health_monitoring_scheduled]
        postcond_add: [crew_physical_health_checked]
        postcond_sub: []

      - name: monitor_crew_mental_health
        precond: [crew_inside_spaceship, health_monitoring_scheduled]
        postcond_add: [crew_mental_health_checked]
        postcond_sub: []

      - name: monitor_crew_fatigue
        precond: [crew_inside_spaceship]
        postcond_add: [crew_fatigue_monitored]
        postcond_sub: []

      - name: check_crew_hydration
        precond: [crew_inside_spaceship]
        postcond_add: [crew_hydration_checked]
        postcond_sub: []

      - name: check_crew_nutrition
        precond: [crew_inside_spaceship]
        postcond_add: [crew_nutrition_checked]
        postcond_sub: []

      - name: transport_crew_to_destination
        precond: [crew_inside_spaceship, airlock_depressurized, crew_suited_for_eva, transport_destination_safe, eva_suit_integrity_checked]
        postcond_add: [crew_outside_spaceship, crew_transport_verified, airlock_pressurized]
        postcond_sub: [crew_inside_spaceship, airlock_depressurized]

      - name: detect_emergency
        precond: []
        postcond_add: [crew_emergency_detected]
        postcond_sub: []

      - name: resolve_emergency
        precond: [crew_emergency_detected, medical_intervention_verified]
        postcond_add: [medical_emergency_resolved]
        postcond_sub: [crew_emergency_detected]

      - name: verify_action_success
        precond: [human_verification_received]
        postcond_add: [crew_transport_verified, medical_intervention_verified, hazard_mitigation_successful]
        postcond_sub: []

      - name: monitor_life_support_systems
        precond: []
        postcond_add: [life_support_nominal]
        postcond_sub: [life_support_failure_detected]

      - name: assist_medical_emergency
        precond: [crew_emergency_detected]
        postcond_add: [medical_intervention_verified]
        postcond_sub: []

      - name: detect_environmental_hazards
        precond: []
        postcond_add: [environmental_hazard_detected]
        postcond_sub: []

      - name: check_eva_suit_integrity
        precond: [crew_suited_for_eva]
        postcond_add: [eva_suit_integrity_checked]
        postcond_sub: []

      - name: manage_inventory
        precond: []
        postcond_add: [inventory_oxygen_nominal, inventory_food_nominal, inventory_medical_kits_nominal]
        postcond_sub: []

      - name: perform_self_diagnostics
        precond: []
        postcond_add: [robot_diagnostics_nominal]
        postcond_sub: [robot_malfunction_detected]

      - name: check_crew_morale
        precond: [crew_inside_spaceship, health_monitoring_scheduled]
        postcond_add: [crew_morale_nominal]
        postcond_sub: []

      - name: detect_radiation_hazard
        precond: []
        postcond_add: [radiation_hazard_detected]
        postcond_sub: []

      - name: perform_autonomous_repairs
        precond: [robot_diagnostics_nominal, systems_malfunction_detected]
        postcond_add: [autonomous_repairs_performed]
        postcond_sub: [systems_malfunction_detected]

      - name: alert_crew_of_hazard
        precond: [environmental_hazard_detected, radiation_hazard_detected]
        postcond_add: [hazard_response_initiated]
        postcond_sub: []

      - name: communicate_hazard_to_ground_control
        precond: [hazard_response_initiated]
        postcond_add: [hazard_communicated_to_ground_control]
        postcond_sub: []

      - name: check_power_system_status
        precond: []
        postcond_add: [power_nominal]
        postcond_sub: [power_critical]

      - name: check_air_quality
        precond: []
        postcond_add: [air_quality_nominal]
        postcond_sub: [air_quality_hazard_detected]

      - name: check_redundant_systems
        precond: []
        postcond_add: [redundant_system_nominal]
        postcond_sub: [redundant_system_failure_detected]

      - name: initiate_ai_self_correction
        precond: [robot_malfunction_detected]
        postcond_add: [ai_self_correction_initiated]
        postcond_sub: []
