model:
  confidence_score:
      successes: 0
      attempts: 0
  states:
      - vehicle_has_gas
      - vehicle_tires_full
      - vehicle_locked
      - human_has_keys
  actions:
      - name: fill_car_with_gas
        precond: []
        postcond_add: [vehicle_has_gas]
        postcond_sub: []
      - name: fill_tires_with_air
        precond: []
        postcond_add: [vehicle_tires_full]
        postcond_sub: []
      - name: lock_vehicle
        precond: [human_has_keys]
        postcond_add: [vehicle_locked]
        postcond_sub: []
