(define (problem task13)
		(:domain everyday_international_travel)

		(:init
			(human_at_house)
			(alternative_route_available)
			(human_experiencing_travel_issue)
			(not (jet_lag_recommendations_given))
			(flight_delayed)
			(human_lost)
			(human_mugged)
			(not (hotel_booked))
			(baggage_lost)
			(not (local_transportation_booked))
		)

		(:goal (and (itinerary_confirmed)
			(human_at_hotel))
		)
)