(define (problem task21)
		(:domain everyday_international_travel)

		(:init
			(human_at_house)
			(alternative_route_available)
			(human_experiencing_travel_issue)
			(not (local_transportation_booked))
			(not (medical_requirements_validated))
			(not (jet_lag_recommendations_given))
			(baggage_lost)
			(not (hotel_booked))
			(not (currency_exchanged))
			(human_mugged)
			(flight_delayed)
		)

		(:goal (and (itinerary_confirmed)
			(human_at_hotel))
		)
)