(define (problem task35)
		(:domain everyday_international_travel)

		(:init
			(human_at_house)
			(alternative_route_available)
			(human_experiencing_travel_issue)
			(not (local_transportation_booked))
			(human_mugged)
			(not (valid_visa))
			(baggage_lost)
			(human_lost)
			(not (currency_exchanged))
			(flight_delayed)
		)

		(:goal (and (itinerary_confirmed)
			(human_at_hotel))
		)
)